export const GET_PERSON_START = "GET_PERSON_START"
export const GET_PERSON_SUCCESS = "GET_PERSON_SUCCESS"
export const GET_PERSON_FAILURE = "GET_PERSON_FAILURE"

export const GET_FILMS_START = "GET_FILMS_START"
export const GET_FILMS_SUCCESS = "GET_FILMS_SUCCESS"
export const GET_FILMS_FAILURE = "GET_FILMS_FAILURE"

export const GET_ALL_CHARACTERS_START = "GET_ALL_CHARACTERS_START"
export const GET_ALL_CHARACTERS_SUCCESS = "GET_ALL_CHARACTERS_SUCCESS"
export const GET_ALL_CHARACTERS_FAILURE = "GET_ALL_CHARACTERS_FAILURE"
